version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:pn12EF74HHI9GcQm5w6effqGtLofb7ENI1Jq6GCAajY"
      - run:
          name: SSH into Server
          command: ssh -o StrictHostKeyChecking=no ubuntu@54.242.132.251 'cd /home/ubuntu/demo-job1 && git pull && pwd && docker-compose up --build -d'
workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
