version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "34:99:28:a2:ec:3e:ca:01:23:e1:9f:cb:9f:b8:2f:59"
      - run:
          name: SSH into Server
          command: ssh -o StrictHostKeyChecking=no ubuntu@13.212.23.59 'cd /home/ubuntu/class-management-fe && git pull && pwd && docker-compose up --build -d'
workflows:
  version: 2
  deploy_workflow:
    jobs:
      - PushImage
