version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:bQ0g019VhHUTuwOPqrIh+osQ+7bJXqKmo6juPF4ib/A"
      - run:
          name: SSH into Server
          command: ssh -o StrictHostKeyChecking=no ubuntu@3.80.97.180 'cd /home/ubuntu/demo-job1 && git pull && pwd && source set_env.sh && echo $POSTGRES_HOST && docker-compose down && docker rmi -f $(docker images -a -q) && docker-compose -f docker-compose-build.yml build --parallel'
      - run:
          name: SSH into Server
          command: ssh -o StrictHostKeyChecking=no ubuntu@3.80.97.180 'cd /home/ubuntu/demo-job1 && source set_env.sh &&  echo $POSTGRES_HOST && docker-compose up -d'
workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
