version: 2.1

jobs:
  PushImage:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build front-end
          command: |
            cd udagram-frontend
            docker build -t datht20fpt/udagram-frontend .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker tag udagram-frontend datht20fpt/udagram-frontend:v1
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
            docker push datht20fpt/udagram-frontend:v1
      - run:
          name: Build feed-backend
          command: |
            cd feed-service
            docker build -t datht20fpt/udagram-api-feed .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
            docker push datht20fpt/udagram-api-feed
      - run:
          name: Build user-backend
          command: |
            cd user-service
            docker build -t datht20fpt/udagram-api-user .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
            docker push datht20fpt/udagram-api-user
      - run:
          name: Build reverseproxy
          command: |
            cd reverse-proxy
            docker build -t datht20fpt/reverseproxy .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
            docker push datht20fpt/reverseproxy
workflows:
  version: 2
  deploy_workflow:
    jobs:
      - PushImage
